apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:1821
    uid: loki
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
  
  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:1822
    uid: prometheus
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
