server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:1821/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ['.*']
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
      - source_labels: ['__meta_docker_container_label_logging_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_logging_exclude']
        regex: 'true'
        action: drop
      # Include ops service logs but with special labeling
      - source_labels: ['__meta_docker_container_name']
        regex: 'ops-.*'
        target_label: 'service'
        replacement: 'ops-service'
      # Add service classification based on container names
      - source_labels: ['__meta_docker_container_name']
        regex: 'viralogic-backend.*'
        target_label: 'service'
        replacement: 'backend'
      - source_labels: ['__meta_docker_container_name']
        regex: 'viralogic-frontend.*'
        target_label: 'service'
        replacement: 'frontend'
      - source_labels: ['__meta_docker_container_name']
        regex: 'rss-service.*'
        target_label: 'service'
        replacement: 'rss-service'
      - source_labels: ['__meta_docker_container_name']
        regex: 'viralogic-celery.*'
        target_label: 'service'
        replacement: 'celery'
      - source_labels: ['__meta_docker_container_name']
        regex: 'viralogic-postgres.*'
        target_label: 'service'
        replacement: 'database'
      - source_labels: ['__meta_docker_container_name']
        regex: 'viralogic-redis.*'
        target_label: 'service'
        replacement: 'cache'
      - source_labels: ['__meta_docker_container_name']
        regex: 'rss-service-postgres.*'
        target_label: 'service'
        replacement: 'rss-database'
      - source_labels: ['__meta_docker_container_name']
        regex: 'rss-service-redis.*'
        target_label: 'service'
        replacement: 'rss-cache'
    pipeline_stages:
      - docker: {}
      - drop:
          expression: '.*GET /health.*'
      - drop:
          expression: '.*health.*HTTP/1\.1.*'

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Application logs (if any are written to files)
  - job_name: applications
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          __path__: /var/log/apps/*.log

  # Custom log files
  - job_name: custom
    static_configs:
      - targets:
          - localhost
        labels:
          job: custom-logs
          __path__: /var/log/custom/*.log
