tunnel: viralogic-production
credentials-file: /etc/cloudflared/viralogic-production-tunnel.json

ingress:
  - hostname: viralogic-api.tbdv.org
    service: http://backend:1720

  - hostname: viralogic.tbdv.org
    service: http://frontend:1721

  - service: http_status:404
