version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viralogic_user -d viralogic"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and message broker
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env.production
    volumes:
      - redis_data:/data
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/viralogic}/backend:${IMAGE_TAG:-latest}
    env_file:
      - .env.production
    volumes:
      - viralogic_logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/viralogic}/frontend:${IMAGE_TAG:-latest}
    env_file:
      - .env.production
    volumes:
      - viralogic_logs:/logs
    depends_on:
      - backend
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celeryworker:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/viralogic}/backend:${IMAGE_TAG:-latest}
    command: celery -A app.celery.celery_app worker --loglevel=info --concurrency=10 -Q celery,auto_post,file_processing,ai_content_generation
    env_file:
      - .env.production
    volumes:
      - viralogic_logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Beat Scheduler
  celerybeat:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/viralogic}/backend:${IMAGE_TAG:-latest}
    command: celery -A app.celery.celery_app beat --loglevel=info
    env_file:
      - .env.production
    volumes:
      - viralogic_logs:/logs
      - celerybeat_data:/var/lib/celery
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Flower for Celery monitoring
  flower:
    image: mher/flower:2.0.1
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/data
    depends_on:
      - redis
      - celeryworker
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - viralogic-network
    restart: unless-stopped

  # Cloudflare Tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro
    network_mode: host  # Required for localhost access to services
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  viralogic_logs:
  celerybeat_data:
  flower_data:

networks:
  viralogic-network:
    driver: bridge
