tunnel: viralogic-production
credentials-file: /etc/cloudflared/viralogic-production-tunnel.json

ingress:
  - hostname: api.viralogic.io
    service: http://backend:1720

  - hostname: viralogic.io
    service: http://frontend:1721

  - hostname: adminer.viralogic.io
    service: http://adminer:1800

  - service: http_status:404
